/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRentalStorage } from "./IRentalStorage";
export type { IWallet } from "./IWallet";
export type { IWalletFactory } from "./IWalletFactory";
export type { RentalStorage } from "./RentalStorage";
export type { TestERC721 } from "./TestERC721";
export type { Wallet } from "./Wallet";
export type { WalletFactory } from "./WalletFactory";
