/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRentalStorage__factory } from "./IRentalStorage__factory";
export { IWallet__factory } from "./IWallet__factory";
export { IWalletFactory__factory } from "./IWalletFactory__factory";
export { RentalStorage__factory } from "./RentalStorage__factory";
export { TestERC721__factory } from "./TestERC721__factory";
export { Wallet__factory } from "./Wallet__factory";
export { WalletFactory__factory } from "./WalletFactory__factory";
